In [1]:

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",20)

In [4]:
# Load Dataset

df = pd.read_excel("online_retail_II(2).xls")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'online_retail_II(2).xls'

In [5]:
import os

print(os.getcwd())

C:\Users\vyjay\Downloads\archive

In [6]:
import os

print(os.listdir())

['.ipynb_checkpoints', '01_data_cleaning.ipynb', 'cleaned_superstore.csv', 'Executive_Report.docx', 'internship.pbix', 'online_retail_II (2).csv', 'SuperStore_Orders.csv', 'SuperStore_Orders.csv.xlsx']

In [7]:
import pandas as pd

df = pd.read_csv("online_retail_II (2).csv")

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df.shape

(1067371, 8)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [10]:
import pandas as pd

df = pd.read_csv(
    "online_retail_II (2).csv",
    parse_dates=["InvoiceDate"]
)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [12]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [13]:
print("Total Revenue:", round(df["Revenue"].sum(),2))
print("Customers:", df["Customer ID"].nunique())
print("Products:", df["StockCode"].nunique())

KeyError: 'Revenue'

In [14]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 34335
Duplicates after: 0

In [15]:
df = df.dropna(subset=["Customer ID"])

In [16]:
df = df.dropna(subset=["Description"])

In [17]:
df = df[df["Quantity"] > 0]
df = df[df["Price"] > 0]

In [18]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [19]:
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month_name()
df["Day"] = df["InvoiceDate"].dt.day_name()
df["Hour"] = df["InvoiceDate"].dt.hour

In [20]:
print(df.shape)

df.isnull().sum()

(779425, 13)

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Revenue        0
Year           0
Month          0
Day            0
Hour           0
dtype: int64

In [21]:
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

(779425, 13)

Missing Values:
Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Revenue        0
Year           0
Month          0
Day            0
Hour           0
dtype: int64

Data Types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
Revenue               float64
Year                    int32
Month                  object
Day                    object
Hour                    int32
dtype: object

In [22]:
df.to_csv("cleaned_data.csv", index=False)

print("✅ cleaned_data.csv saved successfully.")

✅ cleaned_data.csv saved successfully.

In [23]:
print("="*50)
print("CLEANED DATA SUMMARY")
print("="*50)

print(f"Rows               : {len(df):,}")
print(f"Columns            : {df.shape[1]}")
print(f"Customers          : {df['Customer ID'].nunique():,}")
print(f"Products           : {df['StockCode'].nunique():,}")
print(f"Countries          : {df['Country'].nunique():,}")
print(f"Orders             : {df['Invoice'].nunique():,}")
print(f"Total Revenue      : ${df['Revenue'].sum():,.2f}")
print(f"Average Order Value: ${df.groupby('Invoice')['Revenue'].sum().mean():,.2f}")

==================================================
CLEANED DATA SUMMARY
==================================================
Rows               : 779,425
Columns            : 13
Customers          : 5,878
Products           : 4,631
Countries          : 41
Orders             : 36,969
Total Revenue      : $17,374,804.27
Average Order Value: $469.98